[package]
name = "lumx_domain"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
validator = { workspace = true }
