[package]
name = "modules-example"
version = "0.1.0"
edition = "2024"

[dependencies]
lumx_core = { path = "./../../lumx_core" }
lumx_axum = { path = "./../../lumx_axum" }
serde = { version = "1.0", features = ["derive"] }
