[workspace]
members = ["lumx_core", "lumx_sea_orm", "lumx_axum", "examples/*"]
resolver = "2"
exclude = ["examples/**"]

[workspace.dependencies]
log = "0.4"
env_logger = { version = "0.11.5" }
tokio = { version = "1.39", features = ["full"] }
async-trait = "0.1"
tracing = "0.1"
serde = { version = "1.0" }
