[workspace]
members = ["lumx_core", "lumx_sea_orm", "lumx_axum", "examples/*"]
resolver = "2"
exclude = ["examples/**"]

[workspace.dependencies]
async-trait = "0.1"
tokio = { version = "1.39", features = ["full"] }
tracing = "0.1"
