[package]
name = "lumx_axum_test"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
axum = { workspace = true }
lumx_core = { workspace = true }
lumx_axum = { workspace = true }
